"""CVE and non-CVE check implementations."""

from blue_tap.framework.registry import ModuleDescriptor, ModuleFamily, get_registry

_registry = get_registry()


def _register_once(descriptor: ModuleDescriptor) -> None:
    try:
        _registry.get(descriptor.module_id)
    except KeyError:
        _registry.register(descriptor)

_CHECK_DESCRIPTORS = (
    ModuleDescriptor(
        module_id="assessment.cve_airoha",
        family=ModuleFamily.ASSESSMENT,
        name="Airoha RACE Checks",
        description="Probe Airoha RACE surfaces over BLE and BR/EDR",
        protocols=("BLE", "GATT", "RFCOMM"),
        requires=("target",),
        destructive=False,
        requires_pairing=False,
        schema_prefix="blue_tap.vulnscan.result",
        has_report_adapter=False,
        entry_point="blue_tap.modules.assessment.checks.cve_airoha:_check_airoha_race_gatt",
    ),
    ModuleDescriptor(
        module_id="assessment.cve_avrcp",
        family=ModuleFamily.ASSESSMENT,
        name="AVRCP CVE Checks",
        description="Probe AVRCP notification and capability parsing weaknesses",
        protocols=("Classic", "AVRCP", "L2CAP", "SDP"),
        requires=("classic_target",),
        destructive=False,
        requires_pairing=False,
        schema_prefix="blue_tap.vulnscan.result",
        has_report_adapter=False,
        entry_point="blue_tap.modules.assessment.checks.cve_avrcp:_check_avrcp_metamsg_oob",
    ),
    ModuleDescriptor(
        module_id="assessment.cve_ble_smp",
        family=ModuleFamily.ASSESSMENT,
        name="BLE SMP CVE Checks",
        description="Probe BLE SMP pairing-bypass and BR/EDR OOB handling flaws",
        protocols=("BLE", "SMP"),
        requires=("adapter", "ble_target"),
        destructive=False,
        requires_pairing=False,
        schema_prefix="blue_tap.vulnscan.result",
        has_report_adapter=False,
        entry_point="blue_tap.modules.assessment.checks.cve_ble_smp:_check_ble_legacy_pairing_bypass",
    ),
    ModuleDescriptor(
        module_id="assessment.cve_bnep",
        family=ModuleFamily.ASSESSMENT,
        name="BNEP CVE Checks",
        description="Probe BNEP role-swap and heap disclosure behaviors",
        protocols=("Classic", "BNEP", "L2CAP", "SDP"),
        requires=("classic_target",),
        destructive=False,
        requires_pairing=False,
        schema_prefix="blue_tap.vulnscan.result",
        has_report_adapter=False,
        entry_point="blue_tap.modules.assessment.checks.cve_bnep:_check_bnep_role_swap",
    ),
    ModuleDescriptor(
        module_id="assessment.cve_gatt",
        family=ModuleFamily.ASSESSMENT,
        name="GATT CVE Checks",
        description="Probe raw ATT and EATT handling weaknesses",
        protocols=("BLE", "GATT", "ATT", "L2CAP"),
        requires=("ble_target",),
        destructive=False,
        requires_pairing=False,
        schema_prefix="blue_tap.vulnscan.result",
        has_report_adapter=False,
        entry_point="blue_tap.modules.assessment.checks.cve_gatt:_check_bluez_gatt_prep_write_overflow",
    ),
    ModuleDescriptor(
        module_id="assessment.cve_hid",
        family=ModuleFamily.ASSESSMENT,
        name="HID CVE Checks",
        description="Probe Classic HID and BLE HOGP unbonded acceptance paths",
        protocols=("Classic", "BLE", "HID", "GATT", "L2CAP", "SDP"),
        requires=("target",),
        destructive=False,
        requires_pairing=False,
        schema_prefix="blue_tap.vulnscan.result",
        has_report_adapter=False,
        entry_point="blue_tap.modules.assessment.checks.cve_hid:_check_hid_unbonded_connection",
    ),
    ModuleDescriptor(
        module_id="assessment.cve_l2cap",
        family=ModuleFamily.ASSESSMENT,
        name="L2CAP CVE Checks",
        description="Probe L2CAP classic and LE parser edge cases",
        protocols=("Classic", "BLE", "L2CAP", "A2MP"),
        requires=("target",),
        destructive=False,
        requires_pairing=False,
        schema_prefix="blue_tap.vulnscan.result",
        has_report_adapter=False,
        entry_point="blue_tap.modules.assessment.checks.cve_l2cap:_check_l2cap_conf_mtu_info_leak",
    ),
    ModuleDescriptor(
        module_id="assessment.cve_pairing",
        family=ModuleFamily.ASSESSMENT,
        name="Pairing CVE Checks",
        description="Probe pairing-method confusion and silent-pairing weaknesses",
        protocols=("Classic", "BLE", "SMP", "HCI"),
        requires=("adapter", "target"),
        destructive=False,
        requires_pairing=False,
        schema_prefix="blue_tap.vulnscan.result",
        has_report_adapter=False,
        entry_point="blue_tap.modules.assessment.checks.cve_pairing:_check_justworks_silent_pair",
    ),
    ModuleDescriptor(
        module_id="assessment.cve_raw_acl",
        family=ModuleFamily.ASSESSMENT,
        name="Raw ACL CVE Checks",
        description="Probe raw ACL fragmentation behavior via DarkFirmware transport",
        protocols=("Classic", "ACL"),
        requires=("adapter", "classic_target", "darkfirmware"),
        destructive=False,
        requires_pairing=False,
        schema_prefix="blue_tap.vulnscan.result",
        has_report_adapter=False,
        entry_point="blue_tap.modules.assessment.checks.cve_raw_acl:_check_bluefrag_boundary_probe",
    ),
    ModuleDescriptor(
        module_id="assessment.cve_sdp",
        family=ModuleFamily.ASSESSMENT,
        name="SDP CVE Checks",
        description="Probe SDP continuation-state leakage and parser behavior",
        protocols=("Classic", "SDP", "L2CAP"),
        requires=("classic_target",),
        destructive=False,
        requires_pairing=False,
        schema_prefix="blue_tap.vulnscan.result",
        has_report_adapter=False,
        entry_point="blue_tap.modules.assessment.checks.cve_sdp:_check_sdp_continuation_info_leak",
    ),
    ModuleDescriptor(
        module_id="assessment.non_cve_ble",
        family=ModuleFamily.ASSESSMENT,
        name="BLE Posture Checks",
        description="Inspect BLE pairing mode, writable GATT, and EATT posture",
        protocols=("BLE", "GATT", "L2CAP"),
        requires=("ble_target",),
        destructive=False,
        requires_pairing=False,
        schema_prefix="blue_tap.vulnscan.result",
        has_report_adapter=False,
        entry_point="blue_tap.modules.assessment.checks.non_cve_ble:check_pairing_method",
    ),
    ModuleDescriptor(
        module_id="assessment.non_cve_posture",
        family=ModuleFamily.ASSESSMENT,
        name="General Posture Checks",
        description="Inspect PIN lockout, device class, and LMP feature posture",
        protocols=("Classic", "HCI", "LMP", "SDP"),
        requires=("adapter", "target"),
        destructive=False,
        requires_pairing=False,
        schema_prefix="blue_tap.vulnscan.result",
        has_report_adapter=False,
        entry_point="blue_tap.modules.assessment.checks.non_cve_posture:check_pin_lockout",
    ),
    ModuleDescriptor(
        module_id="assessment.non_cve_rfcomm",
        family=ModuleFamily.ASSESSMENT,
        name="RFCOMM Exposure Checks",
        description="Inspect RFCOMM profile reachability, auth, and encryption posture",
        protocols=("Classic", "RFCOMM", "OBEX", "AT", "SDP"),
        requires=("classic_target",),
        destructive=False,
        requires_pairing=False,
        schema_prefix="blue_tap.vulnscan.result",
        has_report_adapter=False,
        entry_point="blue_tap.modules.assessment.checks.non_cve_rfcomm:check_service_exposure",
    ),
)

for _descriptor in _CHECK_DESCRIPTORS:
    _register_once(_descriptor)
